Adding class for pieChart. Adding methods to change its properties,
Rostlab/JS18_ProjectB_Group4 pull request #25
Opened 2018-03-04 14:24 UTC by fhnaseer

pieChart extends ChartBase. Common methods will to ChartBase,

2018-03-04 14:27 UTC, shabnamsadegh commented
can you add the methods to google drive first that we can merge all of them coherently?

2018-03-04 15:33 UTC, shabnamsadegh submitted a review, later dismissed
Before adding to project we need to agree on the structure.

2018-03-04 18:28 UTC, PCXDME requested changes
1. I think data should also be in ChartBase
2. As in slack, I think we should return changes for each method.
Return JSON containing these
-Changes of style
-Changes of layout
-New data (null if no changes to data)
If we do that, then there is no need for getData() and getLayout() anymore because each function returns changes already.

2018-03-08 18:57 UTC, PCXDME approved these changes

2018-03-08 18:58 UTC, merged